// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9v6e3PNUG1T2NOXzOpwLpVFwlEb5mKQA',
    appId: '1:226875687252:web:d32616f507d03e17c008c1',
    messagingSenderId: '226875687252',
    projectId: 'pill-items-fd5cd',
    authDomain: 'pill-items-fd5cd.firebaseapp.com',
    storageBucket: 'pill-items-fd5cd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtZ_HGn63RpP8SWHIKjFFbbQ5TA4EnGeo',
    appId: '1:226875687252:android:eed4606de7d46e11c008c1',
    messagingSenderId: '226875687252',
    projectId: 'pill-items-fd5cd',
    storageBucket: 'pill-items-fd5cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcEZsjFPhoWD5pHQWNN_9tPSlS4mLJx7Q',
    appId: '1:226875687252:ios:85c001888f8334e7c008c1',
    messagingSenderId: '226875687252',
    projectId: 'pill-items-fd5cd',
    storageBucket: 'pill-items-fd5cd.firebasestorage.app',
    iosBundleId: 'com.example.stateManagementExercise',
  );
}
